# Generated by Django 4.2.11 on 2024-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_report_count_reportedpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="description",
            field=models.TextField(max_length=100),
        ),
    ]
