# Generated by Django 4.2.13 on 2024-05-16 13:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0004_post_link_alter_post_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostRecommendation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommend_posts", models.ManyToManyField(blank=True, to="post.post")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PostRecommendation",
                "verbose_name_plural": "PostRecommendations",
                "db_table": "post_recommendation",
            },
        ),
    ]
